### PR TITLE
Update grpcio version

### PR DESCRIPTION
**Pull request by flombardi**
Update grpcio version to fix memory leak when using gRPC streaming API : https://github.com/grpc/grpc/issues/12383

### CODE REVIEW

**Comment by skkumaravel** [comment]
hi Frank,

Have you tested this to see if it works. We did not upgrade past 1.0.0 due to the fact the IOS-XR boxes itself did not support higher versions.

I briefly tested and verified that this version 1.18.0 did not work and I get a unable to connect to the box. I was wondering what you saw

-Karthik

**Comment by flombardi** [comment]
Hi Karthik,

Yes, I have tested and it works for me with IOS-XR 6.3.3 on device "Cisco NCS 5516". I have tested getsubscription (telemetry) and getconfig API.
With version 1.0.0 of grpcio, I have a memory leak when I use the getsubscription API, not with version 1.18.0.

I propose not to set grpcio version. PIP will install the latest version but it allows anyone who wants to install an older version if he encounters problems with his IOS-XR device.

Regards

**Comment by skkumaravel** [comment]
I tried the getconfig on a few different devices with grpcio 1.18.0 and have not gotten it to work.

Devices:
IOS-XR 6.5.1 Cisco NCS 5508
IOS-XR 6.3.2 Cisco NCS 5011

Neither of these two worked. Steps to produce is simply `pip install gprcio==1.18.0` and test grpc_example.py. However this hasn't worked

The reason it was set to 1.0.0 is due to the server version and backwards compatibility. When the version is unset, many people will have issues unless they know to override the grpcio version. If I can reproduce it working then I will release a new version of iosxr_grpc in pypi with the updated version.

**Comment by remingtonc** [comment]
@flombardi We identified the local issue being with 1.0.0 not following proxy environment variables, while updated versions (1.18.0 at least) do. 1.18.0 does work, thanks for the pull and referencing the upstream issue!

To @skkumaravel points, we can say that we have experienced some versioning issues and without comprehensively testing against every version of IOS XR it becomes a little dicey, but we neglected to deep dive into solving or writing down the actual symptoms/when. I am inclined to continue pinning the version, but given our small success 1.18.0 is okay with me. @skkumaravel Propose updating and cutting a new GitHub release and can point to the older release if anyone has issues.

[1.10.1](https://github.com/grpc/grpc/releases/tag/v1.10.1) might be a tentative alternative as it has the minimum bugfix, but I do like being fully up to date. Checking for any official recommendations.

**Review by remingtonc — APPROVED** [review]
PS I approve

**Pull request merged**
